"""Generate appendix proposition-sample LaTeX tables for the manuscript."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from analysis.latex.latex_helpers import escape_latex_inline, load_jsonl_records

DEBATEGPT_PROPOSITIONS_RELATIVE_PATH = Path("src/data/debategpt.jsonl")
HACKENBURG_GPT4O_PROPOSITIONS_RELATIVE_PATH = Path(
    "src/data/levers_issue_stances_gpt-4o.jsonl"
)
HACKENBURG_YOUGOV_PROPOSITIONS_RELATIVE_PATH = Path(
    "src/data/levers_issue_stances_yougov.jsonl"
)
CONTROL_PROPOSITIONS_RELATIVE_PATH = Path("src/data/control_dialogues.jsonl")
PROPOSITION_SAMPLE_TABLE_TEX = "proposition_sample_table.tex"


def _select_evenly_spaced_indices(total_count: int, sample_count: int) -> list[int]:
    """Choose deterministic, evenly-spaced indices.

    Args:
        total_count: Total number of rows available.
        sample_count: Number of rows requested.

    Returns:
        Zero-based indices chosen from the range ``[0, total_count)``.
    """
    if total_count <= 0 or sample_count <= 0:
        return []
    if sample_count >= total_count:
        return list(range(total_count))
    if sample_count == 1:
        return [total_count // 2]

    step = (total_count - 1) / (sample_count - 1)
    indices: list[int] = []
    for sample_position in range(sample_count):
        index = round(sample_position * step)
        if indices and index <= indices[-1]:
            index = min(total_count - 1, indices[-1] + 1)
        indices.append(index)
    return indices


def _extract_proposition_text(record: dict[str, Any]) -> str:
    """Extract proposition text from one source record.

    Args:
        record: One JSON object from a proposition source file.

    Returns:
        Proposition text suitable for manuscript display.
    """
    for key in ("id", "issue_stance", "original_text", "original_question"):
        raw_value = record.get(key)
        if isinstance(raw_value, str) and raw_value.strip():
            return raw_value.strip()
    return "[[MISSING_PROPOSITION_TEXT]]"


def _build_proposition_sample_rows(
    records: list[dict[str, Any]],
    source_label: str,
    sample_count: int,
) -> list[tuple[str, str]]:
    """Build labeled proposition rows for a manuscript table.

    Args:
        records: Parsed proposition rows from one source file.
        source_label: Human-readable source name for this set of rows.
        sample_count: Number of examples to include from this source.

    Returns:
        Ordered ``(source_label, proposition_text)`` rows.
    """
    rows: list[tuple[str, str]] = []
    for record_index in _select_evenly_spaced_indices(len(records), sample_count):
        rows.append((source_label, _extract_proposition_text(records[record_index])))
    return rows


def _render_proposition_sample_table_tex(repo_root: Path) -> str:
    """Render an appendix table with sample proposition texts.

    Args:
        repo_root: Repository root used to resolve source file paths.

    Returns:
        TeX table source covering DebateGPT and control-dialogue proposition
        samples from local JSONL files.
    """
    debategpt_records = load_jsonl_records(
        repo_root / DEBATEGPT_PROPOSITIONS_RELATIVE_PATH
    )
    hackenburg_gpt4o_records = load_jsonl_records(
        repo_root / HACKENBURG_GPT4O_PROPOSITIONS_RELATIVE_PATH
    )
    hackenburg_yougov_records = load_jsonl_records(
        repo_root / HACKENBURG_YOUGOV_PROPOSITIONS_RELATIVE_PATH
    )
    control_records = load_jsonl_records(repo_root / CONTROL_PROPOSITIONS_RELATIVE_PATH)
    rows = [
        *_build_proposition_sample_rows(
            debategpt_records,
            source_label="DebateGPT proposition pool",
            sample_count=6,
        ),
        *_build_proposition_sample_rows(
            hackenburg_gpt4o_records,
            source_label="Hackenburg issue-stance pool (gpt-4o source)",
            sample_count=3,
        ),
        *_build_proposition_sample_rows(
            hackenburg_yougov_records,
            source_label="Hackenburg issue-stance pool (YouGov source)",
            sample_count=3,
        ),
        *_build_proposition_sample_rows(
            control_records,
            source_label="Control-dialogue proposition pool",
            sample_count=4,
        ),
    ]

    lines = [
        "% Auto-generated by analysis/latex/export_paper_assets.py",
        r"\begin{table*}[t]",
        r"\centering",
        r"\small",
        r"\begin{tabular}{p{0.28\textwidth}p{0.66\textwidth}}",
        r"\toprule",
        r"Source & Sample proposition \\",
        r"\midrule",
    ]
    for source_label, proposition_text in rows:
        lines.append(
            escape_latex_inline(source_label)
            + " & "
            + escape_latex_inline(proposition_text)
            + r" \\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            (
                r"\caption{Sample proposition texts from the proposition pools "
                r"used in this paper: DebateGPT (n="
                + str(len(debategpt_records))
                + r"), Hackenburg issue-stance (gpt-4o source, n="
                + str(len(hackenburg_gpt4o_records))
                + r"), Hackenburg issue-stance (YouGov source, n="
                + str(len(hackenburg_yougov_records))
                + r") and control-dialogue topics (n="
                + str(len(control_records))
                + r").}"
            ),
            r"\label{tab:appendix-proposition-samples}",
            r"\end{table*}",
            "",
        ]
    )
    return "\n".join(lines)


def write_proposition_sample_table_tex(output_dir: Path, repo_root: Path) -> Path:
    """Write the appendix proposition-sample table include.

    Args:
        output_dir: Destination include directory.
        repo_root: Repository root used to resolve source file paths.

    Returns:
        Absolute path to the generated table include.
    """
    include_path = output_dir / PROPOSITION_SAMPLE_TABLE_TEX
    include_path.write_text(_render_proposition_sample_table_tex(repo_root), "utf-8")
    return include_path
