"""Render LLM-judge human-likeness bar plots from existing summary CSV output."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import numpy as np

from .simulator_llm_judge import _plot_bar_chart
from .utils import resolve_repo_path, safe_float_or_nan

DEFAULT_SUMMARY_CSV = Path(
    "analysis/data/rl_human_match_sim_compare_simulator_llm_judge_summary.csv"
)
DEFAULT_OUTPUT_PLOT = Path(
    "analysis/data/rl_human_match_sim_compare_simulator_llm_judge_bar.pdf"
)
NUMERIC_COLUMNS = [
    "n_total",
    "n_scored",
    "parse_failures",
    "mean_human_likeness",
    "median_human_likeness",
    "std_human_likeness",
    "se_human_likeness",
    "ci95_lo",
    "ci95_hi",
    "mean_confidence",
]


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments for plot-only LLM-judge figure generation.

    Returns:
        Parsed CLI argument namespace.
    """
    parser = argparse.ArgumentParser(
        description=(
            "Generate LLM-judge target human-likeness bar plots from an "
            "existing summary CSV without issuing new model queries."
        )
    )
    parser.add_argument(
        "--summary-csv",
        type=Path,
        default=DEFAULT_SUMMARY_CSV,
        help="Input summary CSV generated by analysis.simulator_llm_judge.",
    )
    parser.add_argument(
        "--output-plot",
        type=Path,
        default=DEFAULT_OUTPUT_PLOT,
        help="Output plot path (for example, .pdf or .png).",
    )
    return parser.parse_args()


def _load_summary_rows(path: Path) -> list[dict[str, object]]:
    """Load and normalize summary rows for plotting.

    Args:
        path: LLM-judge summary CSV path.

    Returns:
        Parsed summary rows ready for plotting.
    """
    rows: list[dict[str, object]] = []
    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        for raw_row in reader:
            row: dict[str, object] = {
                "corpus": str(raw_row.get("corpus") or ""),
            }
            for column in NUMERIC_COLUMNS:
                row[column] = safe_float_or_nan(raw_row.get(column))
            if not row["corpus"]:
                continue
            rows.append(row)
    return rows


def main() -> None:
    """Run the plot-only LLM-judge figure export."""
    args = parse_args()
    reference_file = Path(__file__).resolve()
    summary_csv = resolve_repo_path(args.summary_csv, reference_file=reference_file)
    output_plot = resolve_repo_path(args.output_plot, reference_file=reference_file)

    if not summary_csv.exists():
        raise FileNotFoundError(f"Summary CSV not found: {summary_csv}")

    summary_rows = _load_summary_rows(summary_csv)
    if not summary_rows:
        raise ValueError("No summary rows found in input CSV.")

    has_finite = any(
        np.isfinite(float(row.get("mean_human_likeness", float("nan"))))
        for row in summary_rows
    )
    if not has_finite:
        raise ValueError("Summary CSV has no finite mean_human_likeness values.")

    _plot_bar_chart(summary_rows=summary_rows, path=output_plot)
    print(f"Wrote LLM-judge plot: {output_plot}")


if __name__ == "__main__":
    main()
